name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 1,5,9,13,17,21 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: x-gopher/github-profile-terminal-action@main
      with:
        feed_url: ""
        twitter_username: czytcn
        theme: dark
        token: ${{ secrets. GITHUB_TOKEN }}
